### ISSUE TITLE
P2P Facets not indexing after updating

### ISSUE THREAD

**Issue by clkmediaco** [petitphp/facetwp-p2p#10]
Updating site to Facetwp v3.8.12 and Facetwp-p2p v3.0.0
Facetwp-p2p sources not indexing from custom post types

**Comment by petitphp** [comment]
Hi @clkmediaco 

Thank for the filling an issue.

Are you using the latest version of FacetWP P2P (3.0.1) ? From which version of FacetWP did you update 3.7.x ou 3.8.x ? In the admin are the P2P sources  still available in the dropdown and are you able to save the settings ?

I'll try to do some testing to see if I can replicate the issue on my end.

**Comment by clkmediaco** [comment]
Thanks for your reply.

Site in question:
https://menumag.com/search-restaurants/

We're using FacetWP v3.8.12 and FacetWP P2P v3.0.0 (latest version on
github that i see). Can you link me to v3.0.1?

We upgraded from FWP 3.1.1 I believe.

The sources are visible in the facet settings, but won't index and aren't
showing on the front end on the latest version of FWP. Saving settings
works fine it appears.

As an experiment, I setup a staging site with a copy of the website in
question, and rolled back FacetWP to 3.55 and then 3.71 and both versions
will index the Posts2Posts facets but i'm not getting them on the search
page.

[image: image.png]

"[Restaurant -> Market] Market" or "market" as the facet name, are not
showing in filters on search pages:

[image: image.png]

One thing I noticed is that we are getting IDs saved in the indexing table
yet they aren't working on the front end which is curious:
[image: image.png]

Not sure what changed in FWP 3.8+ but something is different from these
versions that don't actually recognize the facets to index them properly.

Thanks again.

Cecil

**Comment by petitphp** [comment]
The latest version [available is here](https://github.com/petitphp/facetwp-p2p/releases/tag/3.0.1). Now that you mention it I just realized I forgot to bump the plugin version when creating the release, so you might be good, the plugin version is incorrect in the latest release.

Thanks for the additionnal testing on your side. I'll look at FacetWP 3.8 and check for changes that could break the P2P facets.

**Comment by petitphp** [comment]
A quick update after looking at this.

The initial indexing process is not working when doing a "Re-index" in WordPress admin but its working when using FacetWP WP-CLI command (`wp facetwp index`).

Creating or deleting a connexion between posts is also properly indexed.

I'll be checking why the P2P facets are not indexed when using the "Re-index" button.

**Comment by clkmediaco** [comment]
great thank you for the update and the support on this issue. CK

**Comment by petitphp** [comment]
@clkmediaco 

The issue should be fixed in [the latest release](https://github.com/petitphp/facetwp-p2p/releases/tag/3.0.2).

In summary FacetWP indexing process, when trigger from the setting page, run on the `init` hook which is before P2P `p2p_init` action. So P2P connexions are not registered and the indexing process for P2P facets can't find anything.

**Comment by clkmediaco** [comment]
Thanks for the update @petitphp!

The P2P connection appears to be backward, however.

In my case, my "market" facet should be indexing markets (Panama City, Emerald Coast, etc), but instead, it's indexing restaurants associated with markets.

It does seem to be that the values may be reversed because the facet settings should be:

"[Restaurant → Market] Market"

and not...

"[Restaurant → Market] Restaurant"

However the latter produces the proper facet filter (albeit with IDs instead of names).

I believe the last value in the source (after the closing bracket) is the value you wish to index as your facet correct?

Here's an example of 1 row currently in the index table:

[post_id] => 5143
[facet_value] => 5209
[facet_display_value] => Uncle Ernie's Bayfront Grill

ID 5143 = Panama City Beach
ID 5209 = Uncle Ernie's Bayfront Grill

Where Uncle Ernies is the restaurant.

Using the final value of "Restaurant" in the facet source settings produces the filters but it's using their ID (5143) instead of their name (panama-city-beach) as the facet value.

Thanks again!

**Comment by petitphp** [comment]
Glad the indexing is fixed.

>I believe the last value in the source (after the closing bracket) is the value you wish to index as your facet correct?

Not exactly, the value after the closing bracket if the post type that will be used to find connected items. The facet will end up containing the opposite site of the relation. Here `[Restaurant → Market] Restaurant` will effectively index markets connected to each restaurants.

Initially the idea was the facet would be working like when you want to display [the connected items for a post](https://github.com/scribu/wp-posts-to-posts/wiki/Basic-usage#displaying-connected-pagesposts).

>Using the final value of "Restaurant" in the facet source settings produces the filters but it's using their ID (5143) instead of their name (panama-city-beach) as the facet value.

Yes by default the facet source is [indexed as an ID](https://github.com/petitphp/facetwp-p2p/blob/master/facetwp-p2p.php#L267-L281), but a filter is available if you want to change it before it is inserted in facetwp index table. You should be able to change the source to the name if you need.

**Comment by clkmediaco** [comment]
Ok great. Thanks for the clarification.

Cecil
