### ISSUE TITLE
Posts-to-users - Erreur 500

### ISSUE THREAD

**Issue by MaelysDarde** [petitphp/facetwp-p2p#7]
### Erreur
Lors de l'ajout ou de la suppression d'un lien entre un post et un user, une erreur 500 survient et bloque l'appel AJAX.
`Uncaught Error: Call to undefined method P2P_Side_User::first_post_type() in /app/web/app/plugins/facetwp-p2p/facetwp-p2p.php on line 385`

### Données

L'ajout du lien se fait depuis le post, aucun moyen de sélection présent côté fiche utilisateur.
J'ai ajouté une connexion p2p de type **posts-to-users** (custom post type) comme ceci :

```
p2p_register_connection_type( [
	'name' => 'service_to_users',
	'from' => 'service',
	'to'   => 'user',
] );
```

Enregistrement du custom post type

```
register_post_type(
	'service',
	[
		'label'               => __( 'Services', 'domain' ),
		'labels'              => [
			'name'               => __( 'Services', 'domain' ),
			'singular_name'      => __( 'Service', 'domain' ),
			'add_new'            => __( 'Ajouter un service', 'domain' ),
			'add_new_item'       => __( 'Ajouter un service', 'domain' ),
			'edit_item'          => __( 'Modifier le service', 'domain' ),
			'new_item'           => __( 'Nouveau service', 'domain' ),
			'view_item'          => __( 'Voir le service', 'domain' ),
			'view_items'         => __( 'Voir les services', 'domain' ),
			'search_items'       => __( 'Chercher un service', 'domain' ),
			'not_found'          => __( 'Aucun service trouvé.', 'domain' ),
			'not_found_in_trash' => __( 'Aucun service trouvé dans la poubelle.', 'domain' ),
			'menu_name'          => __( 'Services', 'domain' ),
		],
		'menu_icon'           => 'dashicons-paperclip',
		'public'              => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => false,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'capability_type'     => [ 'service', 'services' ],
		'hierarchical'        => true,
		'supports'            => [ 'title' ],
		'has_archive'         => false,
		'show_in_rest'        => false,
		'menu_position'       => 25,
		'can_export'          => true,
	]
);
```

### Environnement

J'utilise :
- WordPress v5.2.1
- Post-to-posts v1.6.5
- FacetWP v3.3.2
- FacetWP - Posts 2 Posts v2.0.0
- (_FacetWP Map Facet v0.5.1_)
- (_FacetWP Load More v0.4.3_)

**Comment by petitphp** [comment]
@MaelysDarde Merci pour l'issue !

J'ai préparer un fix dans la branche `fix-fatal-p2p-side-user`. Tu peux tester et me dire si ça régle le bug ?

**Comment by MaelysDarde** [comment]
@petitphp C'est tout bon pour moi, je n'ai plus les erreurs et les ajouts/suppressions se font bien

**Comment by petitphp** [comment]
@MaelysDarde Fix en 2.1.1.
