### ISSUE TITLE
Unknown column 'facet_source' in 'where clause'

### ISSUE THREAD

**Issue by MaelysDarde** [petitphp/facetwp-p2p#8]
J'ai une erreur : "Unknown column 'facet_source' in 'where clause'" quand j'utilise la fonction `p2p_delete_connections`. (Je n'ai pu voir l'erreur qu'à travers une commande wp_cli).

En supprimant la ligne 304 (`AND facet_source = %s `) et l'injection de donnée en dessous, la suppression se fait bien et il n'y a plus d'erreur.

Dans la base de données, la colonne "facet_source" n'existe pas (plus ?). La fonction pourrait aussi être simplifiée je pense.

```
Erreur de la base de données WordPress Unknown column 'facet_source' in 'where clause' pour la requête 
DELETE FROM qp2_3_facetwp_index
WHERE post_id IN (28400, 21039)
AND facet_value IN (28400, 21039)
AND facet_source = 'p2p/race_to_result/courses'
faite par [...] FWP_P2P->p2p_delete_connections
```

**Comment by petitphp** [comment]
Corrigé en 3.0.0
